train_file: ['orcal/oracle_classification_chant_train.json']
test_file: ['orcal/oracle_classification_chant_valid.json']
#test_file: ['orcal/oracle_classification_chant_test.json']
data_prefix: '../simclr'
model: 'ImageClassification'
output_path: 'output/image_class_chant_resnet152_base'

image_res: 128
batch_size: 64
img_mode: 'RGB'
dataset_mode: 'classification'

img_random_transform: true
img_mask_ratio: 0.25
img_noise_ratio: -1
img_do_rotate: false
pad_color: 0
vocab_size: 3678

visual_encoder: 'resnet152'
encoder_layer: 12

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 60, min_lr: 1e-4, decay_rate: 1, warmup_lr: 1e-4, warmup_epochs: 20, cooldown_epochs: 0}
