data_path: {
    train: ['train/noise_proc', 'train/label_proc'],
    valid: ['valid/noise_proc', 'valid/label_proc'],
    #test:  ['test/noise', 'test/output'],
    test: ['valid/noise', 'valid/output_scale'],
}

data_prefix: 'handa_sharpen'
output_path: 'output/handa_book_sharpen_unet_scale_256'

image_res: 256
batch_size: 4
img_mode: 'L'
model: 'unet'
scale: true

in_channels: 1
out_channels: 1
bilinear_sample: true

optimizer: {opt: adamW, lr: 1e-3, weight_decay: 1e-8, momentum: 0.9}
schedular: {sched: cosine, lr: 1e-3, epochs: 60, min_lr: 1e-3, decay_rate: 1, warmup_lr: 1e-3, warmup_epochs: 20, cooldown_epochs: 0}
